# Generated by Django 5.0.7 on 2024-08-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruvam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='usertype',
            field=models.IntegerField(default=1),
        ),
    ]
