# Generated by Django 5.0.7 on 2024-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruvam', '0002_alter_register_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
