# Generated by Django 5.0.7 on 2024-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruvam', '0003_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dance_specialization',
            field=models.CharField(choices=[('Choose your specialization', 'Choose your specialization'), ('BA Bharathanatyam', 'BA Bharathanatyam'), ('BA Mohiniyattam', 'BA Mohiniyattam'), ('BA Kuchipudi', 'BA Kuchipudi'), ('BA Kathak', 'BA Kathak'), ('BA Odissi', 'BA Odissi'), ('MA Bharathanatyam', 'MA Bharathanatyam'), ('MA Mohiniyattam', 'MA Mohiniyattam'), ('MA Kuchipudi', 'MA Kuchipudi'), ('MA Kathak', 'MA Kathak'), ('MA Odissi', 'MA Odissi')], default='Choose your specialization', max_length=100),
        ),
    ]
