# Generated by Django 5.0.7 on 2024-09-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruvam', '0004_alter_register_dance_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_title', models.CharField(max_length=200)),
                ('video_link', models.URLField()),
                ('dance_style', models.CharField(choices=[('bharatanatyam', 'Bharatanatyam'), ('mohiniyattam', 'Mohiniyattam'), ('kuchipudi', 'Kuchipudi'), ('kathak', 'Kathak'), ('odissi', 'Odissi')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
