# Generated by Django 5.0.7 on 2024-09-10 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruvam', '0005_danceclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='guru',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danceclass',
            name='image',
            field=models.ImageField(default='', upload_to='dance_class_images/'),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='video_title',
            field=models.TextField(max_length=1000),
        ),
    ]
