# Generated by Django 5.0.7 on 2024-09-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruvam', '0006_danceclass_guru_danceclass_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='guru',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
