# Generated by Django 5.0.7 on 2024-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruvam', '0008_alter_danceclass_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='video_link',
            field=models.URLField(max_length=1000),
        ),
    ]
