# Generated by Django 5.0.7 on 2024-09-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruvam', '0009_alter_danceclass_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='video_link',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
